// export const Music
export const MUSCI_MENU = {
  "all": {
    "name": "全部",
    "type": 0,
    "category": 4,
    "hot": false,
  },
  "sub": [
    {
      "name": "流行",
      "type": 0,
      "category": 5,
      "hot": true,
    },
    {
      "name": "华语",
      "type": 0,
      "category": 5,
      "hot": true,
    },
    {
      "name": "放松",
      "type": 1,
      "category": 5,
      "hot": false,
    },
    {
      "name": "清新",
      "type": 0,
      "category": 5,
      "hot": true,
    },
    {
      "name": "90后",
      "type": 1,
      "category": 5,
      "hot": false,
    },
    {
      "name": "经典",
      "type": 1,
      "category": 5,
      "hot": false,
    },
    {
      "name": "电子",
      "type": 0,
      "category": 5,
      "hot": true,
    },
    {
      "name": "乡村",
      "type": 1,
      "category": 5,
      "hot": false,
    },
    {
      "name": "欧美",
      "type": 1,
      "category": 5,
      "hot": false,
    },
    {
      "name": "轻音乐",
      "type": 0,
      "category": 5,
      "hot": true,
    },
    {
      "name": "流行",
      "type": 0,
      "category": 1,
      "hot": true,
    },
    {
      "name": "影视原声",
      "type": 0,
      "category": 4,
      "hot": true,
    },
    {
      "name": "华语",
      "type": 0,
      "category": 0,
      "hot": true,
    },
    {
      "name": "清晨",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "怀旧",
      "type": 0,
      "category": 3,
      "hot": true,
    },
    {
      "name": "摇滚",
      "type": 0,
      "category": 1,
      "hot": true,
    },
    {
      "name": "夜晚",
      "type": 0,
      "category": 2,
      "hot": true,
    },
    {
      "name": "清新",
      "type": 0,
      "category": 3,
      "hot": true,
    },
    {
      "name": "欧美",
      "type": 1,
      "category": 0,
      "hot": false,
    },
    {
      "name": "学习",
      "type": 0,
      "category": 2,
      "hot": true,
    },
    {
      "name": "民谣",
      "type": 0,
      "category": 1,
      "hot": true,
    },
    {
      "name": "浪漫",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "日语",
      "type": 1,
      "category": 0,
      "hot": false,
    },
    {
      "name": "工作",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "电子",
      "type": 0,
      "category": 1,
      "hot": true,
    },
    {
      "name": "校园",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "韩语",
      "type": 1,
      "category": 0,
      "hot": false,
    },
    {
      "name": "午休",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "游戏",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "粤语",
      "type": 1,
      "category": 0,
      "hot": false,
    },
    {
      "name": "小语种",
      "type": 1,
      "category": 0,
      "hot": false,
    },
    {
      "name": "下午茶",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "治愈",
      "type": 0,
      "category": 3,
      "hot": true,
    },
    {
      "name": "轻音乐",
      "type": 0,
      "category": 1,
      "hot": true,
    },
    {
      "name": "80后",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "放松",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "地铁",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "90后",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "驾车",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "孤独",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "感动",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "运动",
      "type": 0,
      "category": 2,
      "hot": true,
    },
    {
      "name": "乡村",
      "type": 1,
      "category": 1,
      "hot": false,
    },
    {
      "name": "KTV",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "旅行",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "古典",
      "type": 1,
      "category": 1,
      "hot": false,
    },
    {
      "name": "快乐",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "散步",
      "type": 1,
      "category": 2,
      "hot": false,
    },
    {
      "name": "经典",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "安静",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "思念",
      "type": 1,
      "category": 3,
      "hot": false,
    },
    {
      "name": "钢琴",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "榜单",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "00后",
      "type": 1,
      "category": 4,
      "hot": false,
    },
    {
      "name": "古风",
      "type": 1,
      "category": 1,
      "hot": false,
    }
  ],
  "categories": {
    "0": "语种",
    "1": "风格",
    "2": "场景",
    "3": "情感",
    "4": "主题"
  }
}
